// Firey color
block.1 = minecraft:flowing_lava minecraft:lava minecraft:fire

// Torch color
block.2 = minecraft:lit_pumpkin minecraft:torch

// Pure red
block.3 = minecraft:powered_repeater minecraft:redstone_block

// Bright yellows
block.4 = minecraft:glowstone minecraft:lit_redstone_lamp minecraft:observer:powered=true

// Bright blues
block.5 = minecraft:enchanting_table minecraft:beacon minecraft:sea_lantern

// Deep blue-greens
block.6 = minecraft:end_portal minecraft:end_portal_frame minecraft:ender_chest minecraft:end_gateway

// Pure white
block.7 = minecraft:end_rod

// Dim orange
block.8 = minecraft:magma

// Bright purple
block.9 = minecraft:end_crystal