iris.features.required = SSBO COMPUTE_SHADERS CUSTOM_IMAGES

frustum.culling = false

rain.depth = true
beacon.beam.depth = true

clouds = off
sun = false
moon = false
starts = false

texture.composite.colortex10 = minecraft:textures/atlas/blocks.png
texture.composite.colortex11 = minecraft:textures/atlas/blocks_s.png
texture.composite.colortex12 = minecraft:textures/atlas/blocks_n.png

bufferObject.0 = 1048576
bufferObject.1 = 16384
bufferObject.2 = 2097152

image.entityatlas = entityAtlas rgba rgba8 float false false 4096 4096