iris.features.required = SSBO COMPUTE_SHADERS CUSTOM_IMAGES

frustum.culling = false

clouds = off
sun = false
moon = false
starts = false
sky = false
stars = false
oldHandLight = false

allowConcurrentCompute = false

texture.composite.colortex10 = minecraft:textures/atlas/blocks.png
texture.composite.colortex11 = minecraft:textures/atlas/blocks_s.png
texture.composite.colortex12 = minecraft:textures/atlas/blocks_n.png


// Entities
// 12 * 1024 + 8, about 12 KB, entity texture indexing
bufferObject.1 = 12296

// Triangles
// 24 * 2097152, about 25 MB, vertex storage
bufferObject.2 = 50331648 
// 8, triangle + vertex count
bufferObject.3 = 8
// 16 * 2097152, about 17 MB, morton codes + indices
bufferObject.4 = 33554432
// 4 * 2097152 + 1024, about 4 MB, histogram + totals
bufferObject.5 = 8389632
// 33 * 2097152 * 2, about 63 MB, bvh buffer
bufferObject.6 = 138412032
// 4 * 2097152 + 4, about 4 MB, bvh node counters
bufferObject.7 = 8388612


image.entityatlas = entityAtlas rgba rgba8 float false false 4096 4096
image.skyconstants = skyConstants rgba rgba8 float false false 2 2


// RTX settings
//scale.composite1 = REFLECTION_SCALE


// Bloom settings
#ifndef BLOOM
program.composite1.enabled = false
program.composite2.enabled = false
program.composite3.enabled = false
#endif

#if BLOOM_QUALITY == 0
size.buffer.colortex5 = 0.25 0.25
size.buffer.colortex6 = 0.25 0.25
size.buffer.colortex7 = 0.25 0.25
#endif
#if BLOOM_QUALITY == 1
size.buffer.colortex5 = 0.5 0.5
size.buffer.colortex6 = 0.5 0.5
size.buffer.colortex7 = 0.5 0.5
#endif
#if BLOOM_QUALITY == 2
size.buffer.colortex5 = 0.75 0.75
size.buffer.colortex6 = 0.75 0.75
size.buffer.colortex7 = 0.75 0.75
#endif


sliders = BLOOM_QUALITY BLOOM_RADIUS BLOOM_STEP_SIZE BLOOM_INTENSITY BLOOM_THREASHOLD MAX_REFLECTION_TRANSPARENCY_LAYERS REFLECTION_RESOLUTION