iris.features.required = SSBO COMPUTE_SHADERS CUSTOM_IMAGES

frustum.culling = false

rain.depth = true
beacon.beam.depth = true

clouds = off
sun = false
moon = false
starts = false
sky = false
stars = false
oldHandLight = false

texture.composite.colortex10 = minecraft:textures/atlas/blocks.png
texture.composite.colortex11 = minecraft:textures/atlas/blocks_s.png
texture.composite.colortex12 = minecraft:textures/atlas/blocks_n.png

// Entities
// 24 * 8192, about 1 MB, entity vertex storage
bufferObject.0 = 1048576
// 12 * 1024 + 8, about 12 KB, entity texture indexing
bufferObject.1 = 12296

// Blocks
// 24 * 1048576, about 25 MB, vertex storage
bufferObject.2 = 25165824 
// 8, triangle + vertex count
bufferObject.3 = 8
// 16 * 1048576, about 17 MB, morton codes + indices
bufferObject.4 = 16777216
// 4 * 1048576 + 1024, about 4 MB, histogram + totals
bufferObject.5 = 4195328

image.entityatlas = entityAtlas rgba rgba8 float false false 4096 4096
image.skyconstants = skyConstants rgba rgba8 float false false 2 2